
encoder:
  dim: 768
  depth: 12
  heads: 12
  patch_size: 14
  resolution: 224
  n_registers: 1

predictor:
  dim: 768
  depth: 12
  heads: 12
  context: 8
  type: adaln

transform_model:
  dim: 768
  transform_dim: 64
  levels: [8, 5, 5, 5]
  transform_type: vq

data:
  data_root: data/walking_tours/240p_hevc_ext/
  val_root: data/walking_tours/240p_hevc_ext_val/
  sequence_length: 8
  photometric: false
  stride: 1
  step: 1
  resolution: 224
  num_threads: 8
  batch_size: 16

training:
  project: factored-ssl
  seed: 42
  distributed: true
  warmup_steps: 2000
  total_steps: 90000
  gamma: 1e-2
  lambda: 1
  burn_in: 30000
  optimizer: muon
  lr_start: 1e-4
  lr: 4e-4
  lr_end: 1e-6
  wd: 4e-3
  wd_end: 4e-2
  clip_grad: 10.0
  val_fraction: 0.1
  ckpt_fraction: 0.5
  wandb: disabled
