beta: 1e-4
gamma: 1e-6

encoder:
  model_id: "vit_small_patch14_reg4_dinov2.lvd142m"
  dim: 384
  # heads: 12
  # depth: 12
  # registers: 16
  # patch_size: 14

predictor:
  dim: 384
  heads: 12
  depth: 24
  context: 5

transform_model:
  dim: 384
  heads: 6
  depth: 6
  context: 6
  n_transforms: 4
  k: 1
  transform_dim: 128
  transform_type: nf

data:
  data_root: data/walking_tours/240p_hevc_ext/
  val_root: data/walking_tours/240p_hevc_ext_val/
  sequence_length: 6
  photometric: false
  stride: 1
  step: 1
  resolution: 224
  num_threads: 12
  batch_size: 8

training:
  seed: 42
  distributed: true
  warmup_steps: 2000
  total_steps: 90000
  optimizer: muon
  lr_start: 1e-4
  lr: 2e-4
  lr_end: 1e-6
  wd: 4e-3
  wd_end: 4e-2
  clip_grad: 10.0
  val_fraction: 0.05
  # wandb: disabled
