envs:
  # BreakoutNoFrameskip-v4:
  #   env_hz: 60
  #   capture_hz: 2
  #   max_steps: 100
  #   num_episodes: 1000
  #   include_proprioception: false
    
  PointMaze_UMaze-v3:
    env_hz: 10
    capture_hz: 1
    max_steps: 100
    num_episodes: 1000
    include_prop: true

output_dir: "data/env_paths"
frame_size: [224, 224]
