model:
  # in_dim: 128
  dim: 256
  action_dim: 2

data:
  data_path: data/env_paths/pointmaze_umaze_v3.h5
  val_path: data/env_paths/pointmaze_umaze_v3_val.h5
  batch_size: 32
  seq_len: 8
  num_threads: 4
  type: reg

train:
  lr: 2e-3
  wd: 0.05
  epochs: 24
  val_freq: 3
